name: Run lint, build and deploy

on:
  - push
  - pull_request

jobs:
  check-coding-convention:
    name: Check coding convention
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v2
      - name: Install lints
        run: pip install flake8
      - name: Run lint
        run: flake8

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - check-coding-convention
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qdon-prefetch:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/qdon-prefetch:latest
          cache-to: type=inline
